// <auto-generated />
using ElectricBusinessCard.Services.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectricBusinessCard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250819060406_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ElectricBusinessCard.Services.EntityFramework.Models.CategoryWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("CategoryIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("CategoriesWorks");
                });

            modelBuilder.Entity("ElectricBusinessCard.Services.EntityFramework.Models.ElectroWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<int>("PriceInRubles")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(6);

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<int>("WorkIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ElectroWorks");
                });

            modelBuilder.Entity("ElectricBusinessCard.Services.EntityFramework.Models.ElectroWork", b =>
                {
                    b.HasOne("ElectricBusinessCard.Services.EntityFramework.Models.CategoryWork", "Category")
                        .WithMany("Works")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ElectricBusinessCard.Services.EntityFramework.Models.CategoryWork", b =>
                {
                    b.Navigation("Works");
                });
#pragma warning restore 612, 618
        }
    }
}
